sudo: required
services:
  - docker

language: python

python:
  - '3.5'
  - '3.6'

install:
    - pip install -q docker-compose
    - pip install -q -r requirements.txt

script:
    - pytest -v pytorch_server/
    - pytest -v container_tests/
