sudo: required
services:
  - docker

language: python

python:
  - '3.5'
  - '3.6'

install:
    - pip install -q docker-compose
    - pip install -rq requirements.txt

script: pytest pytorch_server/
