sudo: required
services:
  - docker

language: python

python:
  - '3.5'
  - '3.6'

install:
    - pip install docker-compose
    - pip install -r requirements.txt

script: pytest -v --log-level DEBUG pytorch_server/
